name: Build and Obfuscate BPB Panel

on:
  push:
    branches:
      - pre
  schedule:
    # 每天凌晨1:00运行
    - cron: "0 5 * * 2"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: 安装依赖项
        run: |
          npm install -g javascript-obfuscator

      - name: 下载 BPB worker.js
        run: |
          curl -s https://api.github.com/repos/OWNER/REPO/releases \
          | jq -r 'map(select(.prerelease))[0].assets[0].browser_download_url' \
          | xargs wget

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: pre
          commit_message: ':arrow_up: 更新最新的 BPB 面板'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
