name: Sync Latest Pre-release to pre Branch

on:
  workflow_dispatch:

jobs:
  update-pre-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 当前仓库的 pre 分支
        uses: actions/checkout@v3
        with:
          ref: pre

      - name: 安装 jq 和 wget
        run: sudo apt-get update && sudo apt-get install -y jq wget

      - name: 下载最新的 Pre-release 文件
        run: |
          mkdir -p latest_release
          cd latest_release
          urls=$(curl -s https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases \
            | jq -r 'map(select(.prerelease))[0].assets[].browser_download_url')
          
          for url in $urls; do
            echo "下载: $url"
            wget "$url"
          done
          cd ..

      - name: 移动文件到仓库根目录（或你想要的路径）
        run: |
          cp -r latest_release/* ./

      - name: 提交更改到 pre 分支
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update from latest pre-release of BPB-Worker-Panel" || echo "No changes to commit"
          git push origin pre
